<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.xuya</groupId>
        <artifactId>xuya-plus</artifactId>
        <version>1.1.0</version>
    </parent>

    <artifactId>xuya-common</artifactId>
    <packaging>pom</packaging>
    <name>XuYa Common</name>
    <description>公共模块聚合：core（工具/常量）、oss（对象存储）、redis（在线用户/限流）</description>

    <modules>
        <module>xuya-common-core</module>
        <module>xuya-common-oss</module>
        <module>xuya-common-redis</module>
        <module>xuya-common-sensitive</module>
        <module>xuya-common-ratelimiter</module>
        <module>xuya-common-mail</module>
        <module>xuya-common-sms</module>
        <module>xuya-common-encrypt</module>
        <module>xuya-common-web</module>
    </modules>
</project>
